Update pdnsd.spec.in - removed --parents option
rpmbuild fails to build due to --parents option provided to %doc entries in pdnsd.spec.in on Redhat 7.1.  

Removed --parents option.  HTML doc files stored in root of doc directory in RPM, but rpmbuild can now build the package.

Error output:
```
+ cp -pr --parents /home/clarkd/rpmbuild/BUILDROOT/pdnsd-1.2.9a-par.x86_64/usr/share/doc/pdnsd-1.2.9a
cp: missing destination file operand after '/home/clarkd/rpmbuild/BUILDROOT/pdnsd-1.2.9a-par.x86_64/usr/share/doc/pdnsd-1.2.9a'
Try 'cp --help' for more information.
error: Bad exit status from /var/tmp/rpm-tmp.4rg4Xa (%doc)
```